### ISSUE TITLE
Svenja Test

### ISSUE THREAD

**Issue by Ironleaves** [muhkuhxy/ironleaves-photography#147]
- [x] Ipsum verwirrt
- [x] Leidenschaft überflüssig
- [x] Werte bei über mich? Oder weg?
- [x] Versteht Pfeile nicht -> Bedürfnis draufzuklicken
- [x] Navi-Leiste geht ihr zu schnell weg
- [x] Bildlooks (Bildbearbeitungen mehr in den Mittelpunkt rücken?) -> #172 
- [x] DRINNEN bei Standesamtpaket -> Zeitlicher Rahmen reicht aus
- [x] Pfeil im All-inclusive-Paket drinnen -> #173 
- [x] Kontaktformular weiter oben? Es kommt keiner ganz runter (Vielleicht zu viel Footer-Charakter?) -> egal, weil man es schon findet, wenn man's braucht
- [x] Sie würde keinen Onepager machen
- [x] Buttons nicht in der Mitte - besagt der Löffelmesstest; Der sagt nämlich NÖÖÖT -> #174
- [x] Alles andere besteht den Löffelmesstest
